version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "8765:8000"
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=development_secret_key
      - DATABASE_URL=sqlite:///db.sqlite3
      - STATIC_ROOT=/app/staticfiles
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               python manage.py create_mock_data &&
               gunicorn baspana_project.wsgi:application --bind 0.0.0.0:8000"

  client:
    build:
      context: ./client
      args:
        - VITE_API_URL=http://localhost:8765
    ports:
      - "3456:80"
    environment:
      - VITE_API_URL=http://localhost:8765
    depends_on:
      - server
